<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-HRTG6BQ" name="org.example.Runner.Runner" tests="17" failures="3" timestamp="2022-06-28T19:40:21 EET" time="171.219" errors="1">
  <testcase name="runScenario" time="10.207" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="10.440" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="10.257" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="10.052" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="7.513" classname="org.example.Runner.Runner">
    <failure type="java.lang.AssertionError" message="URL of First Slide expected [https://demo.nopcommerce.com/nokia-lumia-1020] but found [https://demo.nopcommerce.com/]">
      <![CDATA[java.lang.AssertionError: URL of First Slide expected [https://demo.nopcommerce.com/nokia-lumia-1020] but found [https://demo.nopcommerce.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.example.StepDefinition.SD6HomeSliders.first_slide_displayed(SD6HomeSliders.java:23)
at ✽.relative product for first slider will displayed(file:///C:/Users/20120/Desktop/proj2/E-CommerceWebAutoTesting/src/main/resources/Features/6-HomeSliders.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="13.396" classname="org.example.Runner.Runner">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Wrong Message expected [Login was unsuccessful. Please correct the errors and try again.
The credentials provided are incorrect] but found [Login was unsuccessful. Please correct the errors and try again.
No customer account found]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Wrong Message expected [Login was unsuccessful. Please correct the errors and try again.
The credentials provided are incorrect] but found [Login was unsuccessful. Please correct the errors and try again.
No customer account found]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at org.example.StepDefinition.SD2Login.cannot_login_successfully(SD2Login.java:59)
at ✽.user not login successfully and go to home page(file:///C:/Users/20120/Desktop/proj2/E-CommerceWebAutoTesting/src/main/resources/Features/2-Login.feature:15)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="9.984" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="10.283" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="10.496" classname="org.example.Runner.Runner">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(ArrayList.java:659)
at java.util.ArrayList.get(ArrayList.java:435)
at org.example.StepDefinition.SD7FollowUs.opens_new_tab(SD7FollowUs.java:23)
at ✽."https://demo.nopcommerce.com/new-online-store-is-open" is opened in new tab(file:///C:/Users/20120/Desktop/proj2/E-CommerceWebAutoTesting/src/main/resources/Features/7-FollowUs.feature:22)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="12.719" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="7.848" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="8.566" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="8.526" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="10.810" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="13.414" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="9.678" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="7.030" classname="org.example.Runner.Runner">
    <failure type="java.lang.AssertionError" message="URL of Second Slide expected [https://demo.nopcommerce.com/iphone-6] but found [https://demo.nopcommerce.com/]">
      <![CDATA[java.lang.AssertionError: URL of Second Slide expected [https://demo.nopcommerce.com/iphone-6] but found [https://demo.nopcommerce.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.example.StepDefinition.SD6HomeSliders.second_slide_displayed(SD6HomeSliders.java:37)
at ✽.relative product for second slider will displayed(file:///C:/Users/20120/Desktop/proj2/E-CommerceWebAutoTesting/src/main/resources/Features/6-HomeSliders.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- org.example.Runner.Runner -->
